CREATE DATABASE INCIDENCIAS;
USE INCIDENCIAS;
CREATE TABLE INCIDENCIA (
	CODIGO INTEGER PRIMARY KEY,
    ESTADO VARCHAR (100) NOT NULL,
    PUESTO VARCHAR (15),
    PROBLEMA VARCHAR(255),
    RESOLUCION VARCHAR(255)
);